# CommandLogger Plugin Configuration
# Webhook settings
webhook:
  url: "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL_HERE"
  
# Admin specified commands to log (without / prefix)
# Only these commands will be sent to webhook
commands:
  - "say"
  - "tell"
  - "msg"
  - "w"
  - "me"
  - "help"
  - "spawn"
  - "home"
  - "tp"
  - "teleport"
  - "gamemode"
  - "give"
  - "kill"
  - "ban"
  - "kick"
  - "op"
  - "deop"
  - "whitelist"
  - "pardon"
  - "unban"

# Discord embed settings
discord:
  bot_name: "Command Logger"
  embed_color: "16711680"
  show_player_head: true
  show_server_info: true
  show_timestamp: true

# Logging settings
logging:
  console_log: true
  log_level: "INFO"
